CREATE DATABASE NANDB
GO
USE NANDB 
GO

CREATE TABLE SONG
( 
	SONGID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	SONGNAME NVARCHAR(MAX),
	SINGERNAME NVARCHAR(MAX),
	SONGURL VARCHAR(MAX),
	DOWNLOADURL VARCHAR(MAX),
	IMAGEURL VARCHAR(MAX),
	SAVEPATH NVARCHAR(MAX),
	DURATION FLOAT,
	POSITION FLOAT
)
ALTER TABLE SONG ADD LIKED BIT

CREATE TABLE UPLOADSONG
( 
	SONGID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	SONGNAME NVARCHAR(MAX),
	SINGERNAME NVARCHAR(MAX),
	IMAGEPATH VARCHAR(MAX),
	SAVEPATH NVARCHAR(MAX),
	DURATION FLOAT,
	POSITION FLOAT
)

CREATE TABLE FEATUREDSONG
(
	SONGID INT NOT NULL PRIMARY KEY
	CONSTRAINT FK_FEATURED_SONG FOREIGN KEY (SONGID) REFERENCES SONG(SONGID)
)

CREATE TABLE NEWSONG
(
	SONGID INT NOT NULL PRIMARY KEY
	CONSTRAINT FK_NEW_SONG FOREIGN KEY (SONGID) REFERENCES SONG(SONGID)
)

CREATE TABLE USERS
(
	USERID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FULLNAME NVARCHAR(MAX),
	USERNAME VARCHAR(MAX),
	PASS VARCHAR(MAX),
	EMAIL VARCHAR(MAX),
	PHONE VARCHAR(50),
	DOB DATETIME,
	SEX VARCHAR(10)
)

CREATE TABLE LIKES
(
	SONGID INT NOT NULL,
	USERID INT NOT NULL,
	CONSTRAINT FK_LIKE_SONG FOREIGN KEY (SONGID) REFERENCES SONG(SONGID),
	CONSTRAINT FK_LIKE_USER FOREIGN KEY (USERID) REFERENCES USERS(USERID)
)

ALTER TABLE LIKES ADD CONSTRAINT PK_LIKES PRIMARY KEY (SONGID, USERID)

CREATE TABLE UPLOAD
(
	SONGID INT NOT NULL,
	USERID INT NOT NULL,
	CONSTRAINT FK_UPLOAD_SONG FOREIGN KEY (SONGID) REFERENCES SONG(SONGID),
	CONSTRAINT FK_UPLOAD_USER FOREIGN KEY (USERID) REFERENCES USERS(USERID)
)

ALTER TABLE UPLOAD DROP CONSTRAINT FK_UPLOAD_SONG
ALTER TABLE UPLOAD ADD CONSTRAINT FK_UPLOAD_SONG FOREIGN KEY (SONGID) REFERENCES UPLOADSONG(SONGID)

ALTER TABLE UPLOAD ADD CONSTRAINT PK_UPLOAD PRIMARY KEY (SONGID, USERID)

CREATE TABLE LASTEST
(
	SONGID INT NOT NULL,
	USERID INT NOT NULL,
	CONSTRAINT FK_LASTEST_SONG FOREIGN KEY (SONGID) REFERENCES SONG(SONGID),
	CONSTRAINT FK_LASTEST_USER FOREIGN KEY (USERID) REFERENCES USERS(USERID)
)

ALTER TABLE LASTEST ADD CONSTRAINT PK_LASTEST PRIMARY KEY (SONGID, USERID)
ALTER TABLE LASTEST ADD SEQ INT

CREATE TABLE PLAYLIST 
(
	PLAYLISTID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	PLAYLISTNAME NVARCHAR(MAX),
	USERID INT NOT NULL,
	CONSTRAINT FK_PLAYLIST_USER FOREIGN KEY (USERID) REFERENCES USERS(USERID)
)

CREATE TABLE PLAYLIST_SONG
(
	SONGID INT NOT NULL,
	PLAYLISTID INT NOT NULL,
	CONSTRAINT FK_SONG FOREIGN KEY (SONGID) REFERENCES SONG(SONGID),
	CONSTRAINT FK_PLAYLIST FOREIGN KEY (PLAYLISTID) REFERENCES PLAYLIST(PLAYLISTID)
)
ALTER TABLE PLAYLIST_SONG ADD CONSTRAINT PK_PLAYLIST_SONG PRIMARY KEY (SONGID, PLAYLISTID)


insert into FEATUREDSONG values (5)
insert into FEATUREDSONG values (4)
insert into FEATUREDSONG values (6)
insert into FEATUREDSONG values (12)
insert into FEATUREDSONG values (7)

insert into NEWSONG values (10)
insert into NEWSONG values (16)
insert into NEWSONG values (21)
insert into NEWSONG values (27)
insert into NEWSONG values (75)

INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Yêu Người Có Ước Mơ', N'buitruonglinh', 'https://www.nhaccuatui.com/bai-hat/yeu-nguoi-co-uoc-mo-buitruonglinh.cauITHa5X8xr.html', 'https://stream.nixcdn.com/Warner_Audio105/YeuNguoiCoUocMo-Buitruonglinh-8209099.mp3?st=ZeB9k8QnQ3e_PnpHybpq5w&e=1670306295', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/07/e/d/4/3/1667805512437.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Yêu Người Có Ước Mơ.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Waiting For You', N'MONO, Onionn', 'https://www.nhaccuatui.com/bai-hat/waiting-for-you-mono-ft-onionn.Mgbb1byycZvy.html', 'https://stream.nixcdn.com/NhacCuaTui2026/WaitingForYou-MONOOnionn-7733882.mp3?st=JdtBcvAe4HF6I3iKOZUjxg&e=1670306291', 'https://avatar-ex-swe.nixcdn.com/song/2022/08/10/4/8/b/1/1660104031203.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Waiting For You.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'dự báo thời tiết hôm nay mưa', N'GREY D', 'https://www.nhaccuatui.com/bai-hat/du-bao-thoi-tiet-hom-nay-mua-grey-d.RLJlaVNBQ9cW.html', 'https://stream.nixcdn.com/NhacCuaTui2031/DuBaoThoiTietHomNayMua-GREYD-8255553.mp3?st=tcz-qoBNTe6lntGfujIcRw&e=1670306041', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/14/4/3/5/a/1668400800081.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\dự báo thời tiết hôm nay mưa.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Chuyện Đôi Ta', N'Emcee L, Muộii', 'https://www.nhaccuatui.com/bai-hat/chuyen-doi-ta-emcee-l-ft-muoii.Efis9AdkuaIA.html', 'https://stream.nixcdn.com/NhacCuaTui1024/ChuyenDoiTa-EmceeLDaLAB-7120974.mp3?st=MKstamymDXWaKpOsn4Yh0w&e=1670306295', 'https://avatar-ex-swe.nixcdn.com/song/2021/11/25/8/7/5/6/1637809824703.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Chuyện Đôi Ta.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Nếu Có Quay Lại', N'Anh Khoa', 'https://www.nhaccuatui.com/bai-hat/neu-co-quay-lai-anh-khoa.YO7oX8pPJVBt.html', 'https://stream.nixcdn.com/NhacCuaTui2032/NeuCoQuayLai-AnhKhoaCover-8313717.mp3?st=3krs3_RLGAfsOVjaf4gbAw&e=1670306224', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/23/8/a/9/3/1669216899218.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Nếu Có Quay Lại.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Cuối Cùng Thì', N'Jack - J97', 'https://www.nhaccuatui.com/bai-hat/cuoi-cung-thi-jack-j97.eCLmz3VIsxoY.html', 'https://stream.nixcdn.com/NhacCuaTui2031/CuoiCungThi-JackJ97-8207352.mp3?st=lh3bupdjdCjB20uiRLStGA&e=1670306219', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/07/e/d/4/3/1667802740293.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Cuối Cùng Thì.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'U Mê Em', N'Kay Trần', 'https://www.nhaccuatui.com/bai-hat/u-me-em-kay-tran.vwrXWDDu5bVj.html', 'https://stream.nixcdn.com/Warner_Audio113/UMeEm-KayTran-8356704.mp3?st=EPuQeGcl448gaTFbkRDZXA&e=1670306197', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/30/d/4/5/0/1669803551785.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\U Mê Em.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Người Như Anh', N'Mai Tiến Dũng', 'https://www.nhaccuatui.com/bai-hat/nguoi-nhu-anh-mai-tien-dung.0bA1tDdM2z71.html', 'https://stream.nixcdn.com/NhacCuaTui2030/NguoiNhuAnh-MaiTienDung-8095883.mp3?st=neZ-G6SjxsXY6WoC5yXUKg&e=1670306041', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/20/2/4/1/e/1666252139527.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Người Như Anh.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Chết Trong Em', N'Thịnh Suy', 'https://www.nhaccuatui.com/bai-hat/chet-trong-em-thinh-suy.vHnHrQHsL81j.html', 'https://stream.nixcdn.com/Believe_Audio157/ChetTrongEm-ThinhSuy-8261960.mp3?st=bgHt5VY3fYudAcBSz-EZZQ&e=1670306041', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/01/e/b/7/c/1667274782517.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Chết Trong Em.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Chưa Quên Người Yêu Cũ', N'Hà Nhi', 'https://www.nhaccuatui.com/bai-hat/chua-quen-nguoi-yeu-cu-ha-nhi.GZZTzUhClujD.html', 'https://stream.nixcdn.com/NhacCuaTui2025/ChuaQuenNguoiYeuCu-HaNhi-7662060.mp3?st=YSvYW5iV6kEjGft93DvOcw&e=1670306041', 'https://avatar-ex-swe.nixcdn.com/song/2022/07/28/3/b/5/b/1658997436153.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Chưa Quên Người Yêu Cũ.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Một Đêm Say', N'Thịnh Suy', 'https://www.nhaccuatui.com/bai-hat/mot-dem-say-thinh-suy.5n3elt2khD4C.html', 'https://stream.nixcdn.com/Believe_Audio126/MotDemSayX-ThinhSuy-7978425.mp3?st=SvTbCd2bPExF_hgnOY3kfg&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2019/05/21/f/8/9/2/1558428770556.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Một Đêm Say.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Bài Này Không Để Đi Diễn', N'Anh Tú Atus', 'https://www.nhaccuatui.com/bai-hat/bai-nay-khong-de-di-dien-anh-tu-atus.pcsIRDtZvW0y.html', 'https://stream.nixcdn.com/NhacCuaTui2029/BaiNayKhongDeDiDien-AnhTuAtus-8076045.mp3?st=2sGmOpQZDl4sLMddZ5TS7g&e=1670306041', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/17/b/9/5/f/1665981317873.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Bài Này Không Để Đi Diễn.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Hồi Kết', N'Hà Nhi', 'https://www.nhaccuatui.com/bai-hat/hoi-ket-ha-nhi.WTJs7Kyyqa95.html', 'https://stream.nixcdn.com/Sony_Audio111/HoiKet-HaNhi-8274211.mp3?st=lfrcmNawMM4VwEpyCHlX2A&e=1670306321', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/15/7/7/d/e/1668497734639.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Hồi Kết.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Tình Yêu Đến Sau', N'Myra Trần', 'https://www.nhaccuatui.com/bai-hat/tinh-yeu-den-sau-myra-tran.edXbzYcbz0s5.html', 'https://stream.nixcdn.com/NhacCuaTui2031/TinhYeuDenSau-MyraTran-8294285.mp3?st=uCwMynGYb1ETBkf177bVug&e=1670306048', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/21/4/f/d/3/1669004664657.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Tình Yêu Đến Sau.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Anh Tự Do Nhưng Cô Đơn', N'Trung Quân', 'https://www.nhaccuatui.com/bai-hat/anh-tu-do-nhung-co-don-trung-quan.TCvfU1mbiFaY.html', 'https://stream.nixcdn.com/NhacCuaTui2031/AnhTuDoNhungCoDon-TrungQuanIdol-8246003.mp3?st=HH_36HAP-B_IC2Z0SxwSxg&e=1670306041', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/10/7/f/f/e/1668054031624.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Anh Tự Do Nhưng Cô Đơn.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Em Là', N'MONO, Onionn', 'https://www.nhaccuatui.com/bai-hat/em-la-mono-ft-onionn.mD4f72qH0Cwp.html', 'https://stream.nixcdn.com/NhacCuaTui2026/EmLa-MONOOnionn-7736094.mp3?st=wKtkmt4YaC-i_SgA0YbuAA&e=1670306041', 'https://avatar-ex-swe.nixcdn.com/song/2022/08/10/4/8/b/1/1660119775021.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Em Là.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Đáp Án Cuối Cùng', N'Quân A.P', 'https://www.nhaccuatui.com/bai-hat/dap-an-cuoi-cung-quan-ap.I9uo47SekQLW.html', 'https://stream.nixcdn.com/NhacCuaTui2028/DapAnCuoiCung-QuanAP-7887096.mp3?st=QzGSHW9WvfoD1m2RQng1Rw&e=1670306321', 'https://avatar-ex-swe.nixcdn.com/song/2022/09/16/0/2/1/c/1663300860128.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Đáp Án Cuối Cùng.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Cô Đơn Trên Sofa', N'Hồ Ngọc Hà', 'https://www.nhaccuatui.com/bai-hat/co-don-tren-sofa-ho-ngoc-ha.Kj5jUREVKNbs.html', 'https://stream.nixcdn.com/NhacCuaTui2029/CoDonTrenSofa-HoNgocHa-8093720.mp3?st=jJlvmpDzU9IYTvFfa4JLXA&e=1670306041', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/19/7/1/f/4/1666185034236.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Cô Đơn Trên Sofa.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Vaicaunoicokhiennguoithaydoi', N'GREY D, tlinh', 'https://www.nhaccuatui.com/bai-hat/vaicaunoicokhiennguoithaydoi-grey-d-ft-tlinh.Vbs1N4O5p8bH.html', 'https://stream.nixcdn.com/NhacCuaTui2023/Vaicaunoicokhiennguoithaydoi-GREYDDoanTheLanTlinh-7533673.mp3?st=T9iTw9CVzjOtHDwmdg35Ww&e=1670306041', 'https://avatar-ex-swe.nixcdn.com/song/2022/06/20/f/c/8/c/1655699296267.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Vaicaunoicokhiennguoithaydoi.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Tôi Thấy Hoa Vàng Trên Cỏ Xanh (XHTDRLX2)', N'Ái Phương, Trúc Nhân', 'https://www.nhaccuatui.com/bai-hat/toi-thay-hoa-vang-tren-co-xanh-xhtdrlx2-ai-phuong-ft-truc-nhan.NxeadbY8mpmi.html', 'https://stream.nixcdn.com/Sony_Audio111/ToiThayHoaVangTrenCoXanh-TrucNhanAiPhuong-8275771.mp3?st=Khdb5uYvvANYJkra1qHjrw&e=1670306197', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/08/8/a/6/f/1667896470362.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Tôi Thấy Hoa Vàng Trên Cỏ Xanh (XHTDRLX2).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Ừ! Em Xin Lỗi', N'Hoàng Yến Chibi, B Ray, Khắc Hưng', 'https://www.nhaccuatui.com/bai-hat/u-em-xin-loi-hoang-yen-chibi-ft-b-ray-ft-khac-hung.960qfsb9WJFs.html', 'https://stream.nixcdn.com/Believe_Audio136/UEmXinLoi-HoangYenChibi-8083102.mp3?st=1gfgqNlopavR2rv73fKOEg&e=1670306321', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/18/1/8/c/8/1666088294330.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Ừ! Em Xin Lỗi.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Sao Cũng Được', N'Thành Đạt', 'https://www.nhaccuatui.com/bai-hat/sao-cung-duoc-thanh-dat.3M9K4epclADQ.html', 'https://stream.nixcdn.com/NhacCuaTui2029/SaoCungDuoc-ThanhDat-8072594.mp3?st=8wWUXLwQ-zrm3VNOk8Ei9g&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/16/5/e/5/8/1665933114579.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Sao Cũng Được.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Hãy Trao Cho Anh', N'Sơn Tùng M-TP, Snoop Dogg', 'https://www.nhaccuatui.com/bai-hat/hay-trao-cho-anh-son-tung-m-tp-ft-snoop-dogg.vtEybe9NxLw7.html', 'https://stream.nixcdn.com/NhacCuaTui985/HayTraoChoAnh-SonTungMTPSnoopDogg-6010660.mp3?st=rgCNywyrcohnEN_1oYRjPA&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2019/07/03/7/5/b/e/1562137543919.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Hãy Trao Cho Anh.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Người Tình Mùa Đông', N'Đức Phúc, MONO, DTAP', 'https://www.nhaccuatui.com/bai-hat/nguoi-tinh-mua-dong-duc-phuc-ft-mono-ft-dtap.cbko3IzRDwtw.html', 'https://stream.nixcdn.com/NhacCuaTui2032/NguoiTinhMuaDong-DucPhucMONODTAP-8343704.mp3?st=JCPvPo96GL2MMuO7EXbzdQ&e=1670306321', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/29/8/9/b/8/1669712534560.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Người Tình Mùa Đông.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Một Ngàn Nỗi Đau', N'Văn Mai Hương, Hứa Kim Tuyền', 'https://www.nhaccuatui.com/bai-hat/mot-ngan-noi-dau-van-mai-huong-ft-hua-kim-tuyen.jvaolomZtGnd.html', 'https://stream.nixcdn.com/NhacCuaTui2023/MotNganNoiDau-VanMaiHuongHuaKimTuyen-7561897.mp3?st=frIdcgY6NV7q6sMlnCucCg&e=1670306048', 'https://avatar-ex-swe.nixcdn.com/song/2022/06/22/2/2/2/d/1655884422688.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Một Ngàn Nỗi Đau.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Vì Mẹ Anh Bắt Chia Tay', N'Miu Lê, Karik, Châu Đăng Khoa', 'https://www.nhaccuatui.com/bai-hat/vi-me-anh-bat-chia-tay-miu-le-ft-karik-ft-chau-dang-khoa.gYMcjxHNy3sl.html', 'https://stream.nixcdn.com/NhacCuaTui2022/ViMeAnhBatChiaTay-MiuLe-7503053.mp3?st=51BmNpPwpPXcmKZgE50EKg&e=1670306173', 'https://avatar-ex-swe.nixcdn.com/song/2022/06/16/d/c/9/2/1655371095601.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Vì Mẹ Anh Bắt Chia Tay.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Lỡ Duyên Kiếp Này, Liệu Có Kiếp Sau', N'Khả Hiệp', 'https://www.nhaccuatui.com/bai-hat/lo-duyen-kiep-nay-lieu-co-kiep-sau-kha-hiep.buDKWJBYoM3N.html', 'https://stream.nixcdn.com/Believe_Audio166/LoDuyenKiepNayLieuCoKiepSau-KhaHiep-8340080.mp3?st=FV21A_iM6GUA5N3epDeszQ&e=1670306321', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/18/5/2/9/8/1668758147198.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Lỡ Duyên Kiếp Này, Liệu Có Kiếp Sau.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Có Chơi Có Chịu', N'Karik, OnlyC', 'https://www.nhaccuatui.com/bai-hat/co-choi-co-chiu-karik-ft-onlyc.2oumKK6kwPCl.html', 'https://stream.nixcdn.com/NhacCuaTui2028/CoChoiCoChiu-KarikOnlyC-7976227.mp3?st=sJpCoubkaveUjXhBYZWCvA&e=1670306173', 'https://avatar-ex-swe.nixcdn.com/song/2022/09/26/a/b/1/3/1664174361775.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Có Chơi Có Chịu.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Tòng Phu', N'Keyo', 'https://www.nhaccuatui.com/bai-hat/tong-phu-keyo.MPetbhMSqW15.html', 'https://stream.nixcdn.com/NhacCuaTui2027/TongPhu-KeyoVietNam-7802406.mp3?st=34A7ReVRmPi24s2tFUoFYQ&e=1670306197', 'https://avatar-ex-swe.nixcdn.com/song/2022/08/18/f/9/4/5/1660831802969.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Tòng Phu.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Chạy Ngay Đi', N'Sơn Tùng M-TP', 'https://www.nhaccuatui.com/bai-hat/chay-ngay-di-son-tung-m-tp.fuwWtPb4h3B2.html', 'https://stream.nixcdn.com/NhacCuaTui964/ChayNgayDi-SonTungMTP-5468704.mp3?st=rzVIYWhCp88u7kt51f2sKw&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2018/05/12/e/8/6/f/1526059033533.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Chạy Ngay Đi.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Dù Cho Mai Về Sau (Acoustic Version)', N'buitruonglinh', 'https://www.nhaccuatui.com/bai-hat/du-cho-mai-ve-sau-acoustic-version-buitruonglinh.qz5ZUkmk2Eh3.html', 'https://stream.nixcdn.com/NhacCuaTui1007/DuChoMaiVeSauAcousticVersion-buitruonglinh-6853567.mp3?st=8-cMWshN5P2mZJJxBLCx3g&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2020/11/30/f/f/2/6/1606727675173.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Dù Cho Mai Về Sau (Acoustic Version).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Yêu Đương Khó Quá Thì Chạy Về Khóc Với Anh', N'ERIK', 'https://www.nhaccuatui.com/bai-hat/yeu-duong-kho-qua-thi-chay-ve-khoc-voi-anh-erik.B6rEC4ZEO7oD.html', 'https://stream.nixcdn.com/NhacCuaTui1025/YeuDuongKhoQuaThiChayVeKhocVoiAnh-ERIK-7128950.mp3?st=TMmUV-BwYLhl7J8Dr_8aVQ&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2022/01/26/4/e/f/e/1643184497199.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Yêu Đương Khó Quá Thì Chạy Về Khóc Với Anh.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Muộn Rồi Mà Sao Còn', N'Sơn Tùng M-TP', 'https://www.nhaccuatui.com/bai-hat/muon-roi-ma-sao-con-son-tung-m-tp.6nAqBAZ3nxuV.html', 'https://stream.nixcdn.com/Believe_Audio19/MuonRoiMaSaoCon-SonTungMTP-7011803.mp3?st=JX2-MWj8rqTPaI-npBrw7Q&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2021/04/29/9/1/f/8/1619691182261.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Muộn Rồi Mà Sao Còn.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Chân Ái', N'Orange, Khói, Châu Đăng Khoa', 'https://www.nhaccuatui.com/bai-hat/chan-ai-orange-ft-khoi-ft-chau-dang-khoa.ybwdIMjKeYD9.html', 'https://stream.nixcdn.com/NhacCuaTui995/ChanAi-OrangeKhoi-6225088.mp3?st=W7w-bMvU1UcM-9Wj7Krcew&e=1670306048', 'https://avatar-ex-swe.nixcdn.com/song/2020/02/17/f/6/a/4/1581934405838.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Chân Ái.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Cứu Vãn Kịp Không', N'Vương Anh Tú', 'https://www.nhaccuatui.com/bai-hat/cuu-van-kip-khong-vuong-anh-tu.P7vVAGwWK1sQ.html', 'https://stream.nixcdn.com/NhacCuaTui2028/CuuVanKipKhong-VuongAnhTu-7847996.mp3?st=W6LHiL_xA2G8r6monzBshg&e=1670306048', 'https://avatar-ex-swe.nixcdn.com/song/2022/09/07/b/d/f/6/1662537457511.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Cứu Vãn Kịp Không.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Dạ Vũ', N'Tăng Duy Tân', 'https://www.nhaccuatui.com/bai-hat/da-vu-tang-duy-tan.8Q8yLCcES92H.html', 'https://stream.nixcdn.com/Warner_Audio72/DaVu-TangDuyTan-7068051.mp3?st=2cEbOrW_ILPlg6NV6dz2Hg&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2021/08/15/a/7/9/2/1629021746388.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Dạ Vũ.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Đế Vương', N'Đình Dũng, ACV', 'https://www.nhaccuatui.com/bai-hat/de-vuong-dinh-dung-ft-acv.w8lmuII1Yn2G.html', 'https://stream.nixcdn.com/NhacCuaTui1024/DeVuong-DinhDungACV-7121634.mp3?st=G6dTfsRC3tQ0mvdqa_AlqA&e=1670306048', 'https://avatar-ex-swe.nixcdn.com/song/2021/11/29/a/9/5/0/1638180197658.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Đế Vương.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'hai mươi hai (22)', N'Hứa Kim Tuyền, AMEE', 'https://www.nhaccuatui.com/bai-hat/hai-muoi-hai-22-hua-kim-tuyen-ft-amee.kvyyApgfnHC3.html', 'https://stream.nixcdn.com/NhacCuaTui2022/HaiMuoiHai22-HuaKimTuyenAMEE-7231237.mp3?st=oAwcqaoe4u3m88B5rN6X8A&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/05/24/9/6/e/a/1653363505428.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\hai mươi hai (22).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Là Do Em Xui Thôi', N'Khói, Sofia, Châu Đăng Khoa', 'https://www.nhaccuatui.com/bai-hat/la-do-em-xui-thoi-khoi-ft-sofia-ft-chau-dang-khoa.JIxy8QxschdZ.html', 'https://stream.nixcdn.com/NhacCuaTui1025/LaDoEmXuiThoi-KhoiSofiaDanTrangChauDangKhoa-7125647.mp3?st=tttngGpOY-MJGmzfniUpgg&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/01/25/b/f/4/a/1643078471057.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Là Do Em Xui Thôi.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Bước Qua Nhau', N'Vũ', 'https://www.nhaccuatui.com/bai-hat/buoc-qua-nhau-vu.EdENCgJm9dAa.html', 'https://stream.nixcdn.com/Warner_Audio86/BuocQuaNhau-Vu-7847964.mp3?st=RhylqiecIVOGk6ejltKZYg&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2021/11/19/6/d/9/1/1637317177185.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Bước Qua Nhau.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'lời tạm biệt chưa nói', N'GREY D, Orange', 'https://www.nhaccuatui.com/bai-hat/loi-tam-biet-chua-noi-grey-d-ft-orange.ENwwBWpgDXnz.html', 'https://stream.nixcdn.com/NhacCuaTui2025/LoiTamBietChuaNoi-GREYDDoanTheLanOrange-7613756.mp3?st=z9-MDEHPfln6r7IqneQkKQ&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/07/21/a/a/7/5/1658391970153.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\lời tạm biệt chưa nói.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Chuyện Rằng', N'Thịnh Suy', 'https://www.nhaccuatui.com/bai-hat/chuyen-rang-thinh-suy.4yr3Kru4RDD1.html', 'https://stream.nixcdn.com/NhacCuaTui1007/ChuyenRang1-ThinhSuy-6465355.mp3?st=1CHuPZzlWiN_OQOjZbeoJA&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2020/08/07/d/e/f/2/1596786667818.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Chuyện Rằng.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Tệ Thật, Anh Nhớ Em', N'Thanh Hưng', 'https://www.nhaccuatui.com/bai-hat/te-that-anh-nho-em-thanh-hung.XPRKMZKQfBt5.html', 'https://stream.nixcdn.com/NhacCuaTui1026/TeThatAnhNhoEm-ThanhHung-7132634.mp3?st=HHWsc8jnIjjrIhPWvd3Jyg&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/03/03/0/1/3/6/1646267009685.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Tệ Thật, Anh Nhớ Em.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Ai Rồi Cũng Sẽ Khác (Live in Giao Lộ Thời Gian 2022)', N'Hà Nhi', 'https://www.nhaccuatui.com/bai-hat/ai-roi-cung-se-khac-live-in-giao-lo-thoi-gian-2022-ha-nhi.5LrLCejcdYVh.html', 'https://stream.nixcdn.com/NhacCuaTui2029/AiRoiCungSeKhacCover-HaNhi-8074594.mp3?st=_Rikgd7GeMTx_8PQhpcxcA&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/singer/avatar/2022/06/07/7/1/4/6/1654588529598.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Ai Rồi Cũng Sẽ Khác (Live in Giao Lộ Thời Gian 2022).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Khó Vẽ Nụ Cười', N'Đạt G, Du Uyên', 'https://www.nhaccuatui.com/bai-hat/kho-ve-nu-cuoi-dat-g-ft-du-uyen.jyzUEf5T3rMu.html', 'https://stream.nixcdn.com/Sony_Audio66/KhoVeNuCuoi-DatGDuUyen-6114344.mp3?st=VhV534gi-ea2oozHoRtVvw&e=1670306197', 'https://avatar-ex-swe.nixcdn.com/song/2019/09/17/b/a/5/a/1568694782034.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Khó Vẽ Nụ Cười.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Như Anh Đã Thấy Em', N'PhucXP, Freak D', 'https://www.nhaccuatui.com/bai-hat/nhu-anh-da-thay-em-phucxp-ft-freak-d.gh6kSYivNF7Y.html', 'https://stream.nixcdn.com/NhacCuaTui2022/NhuAnhDaThayEm-PhucXPFreakD-7370334.mp3?st=v6zGC9kAg01SbkAd7YFBjQ&e=1670306197', 'https://avatar-ex-swe.nixcdn.com/song/2022/06/08/0/0/9/1/1654684969581.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Như Anh Đã Thấy Em.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Câu Hứa Chưa Vẹn Tròn', N'Phát Huy T4', 'https://www.nhaccuatui.com/bai-hat/cau-hua-chua-ven-tron-phat-huy-t4.tnP3A32iG5Wz.html', 'https://stream.nixcdn.com/NhacCuaTui1022/CauHuaChuaVenTron-PhatHuyT4-7093319.mp3?st=b9teTU6HjT6JQCyyZV9R2Q&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2021/09/23/b/9/f/5/1632384189938.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Câu Hứa Chưa Vẹn Tròn.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Hoa Nở Không Màu', N'Hoài Lâm', 'https://www.nhaccuatui.com/bai-hat/hoa-no-khong-mau-hoai-lam.qbK16hjg5TdZ.html', 'https://stream.nixcdn.com/NhacCuaTui999/HoaNoKhongMau1-HoaiLam-6281704.mp3?st=S-D8kEmgagSt-6wo3LAomA&e=1670306321', 'https://avatar-ex-swe.nixcdn.com/song/2020/05/15/c/f/3/0/1589532035884.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Hoa Nở Không Màu.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'tiny love', N'Thịnh Suy', 'https://www.nhaccuatui.com/bai-hat/tiny-love-thinh-suy.VNPqe8Hq0FRq.html', 'https://stream.nixcdn.com/NhacCuaTui1024/TinyLove-ThinhSuy-7122314.mp3?st=7ezGsvFJDoctFlWL8E_nXA&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2021/12/03/6/8/e/4/1638519606788.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\tiny love.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Đến Giờ Cơm (XHTDRLX2)', N'Ái Phương', 'https://www.nhaccuatui.com/bai-hat/den-gio-com-xhtdrlx2-ai-phuong.Khs3xE4ioZxi.html', 'https://stream.nixcdn.com/Sony_Audio111/DenGioCom-AiPhuong-8275778.mp3?st=I7lEhT8V4t6I20UKoDL0CQ&e=1670306321', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/17/0/5/b/e/1668665119661.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Đến Giờ Cơm (XHTDRLX2).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Kết Thúc Bắt Đầu', N'Da LAB, Đức Phúc', 'https://www.nhaccuatui.com/bai-hat/ket-thuc-bat-dau-da-lab-ft-duc-phuc.OLkel2SQBpLD.html', 'https://stream.nixcdn.com/NhacCuaTui2030/KetThucBatDau-DaLABDucPhuc-8114291.mp3?st=L6VpJeqsZNuhN0pO9GbOXw&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/25/5/3/7/f/1666670692482.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Kết Thúc Bắt Đầu.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Mỗi Khi Anh Nhìn Em', N'Mỹ Anh', 'https://www.nhaccuatui.com/bai-hat/moi-khi-anh-nhin-em-my-anh.nDzgl5PntBth.html', 'https://stream.nixcdn.com/NhacCuaTui2030/MoiKhiAnhNhinEm-MyAnh-8182187.mp3?st=2zxxEo_gi0JfZL_BqN9RbA&e=1670306321', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/31/8/3/d/0/1667212019298.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Mỗi Khi Anh Nhìn Em.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Trót Trao Duyên', N'NB3 Hoài Bảo', 'https://www.nhaccuatui.com/bai-hat/trot-trao-duyen-nb3-hoai-bao.nDoENErlvG27.html', 'https://stream.nixcdn.com/NhacCuaTui2031/TrotTraoDuyen-NB3HoaiBao-8246273.mp3?st=I8NbcHGXwoQcrBqK6rnmng&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/10/7/f/f/e/1668092345420.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Trót Trao Duyên.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Nàng Thơ', N'Hoàng Dũng', 'https://www.nhaccuatui.com/bai-hat/nang-tho-hoang-dung.Kx3Kbih0rS5z.html', 'https://stream.nixcdn.com/NhacCuaTui1001/NangTho-HoangDung-6413381.mp3?st=SfTA_R05fIuMhexMxPkdIQ&e=1670306045', 'https://avatar-ex-swe.nixcdn.com/song/2020/07/31/c/5/8/9/1596188259603.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Nàng Thơ.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Anh Chưa Thương Em Đến Vậy Đâu (Cover)', N'Trung Hiếu', 'https://www.nhaccuatui.com/bai-hat/anh-chua-thuong-em-den-vay-dau-cover-trung-hieu.8jT242OhahOQ.html', 'https://stream.nixcdn.com/NhacCuaTui2029/AnhChuaThuongEmDenVayDauCover-TrungHieu-8037651.mp3?st=NcVnblHjf-SvTyfFA8dYlQ&e=1670306197', 'https://stc-id.nixcdn.com/v11/images/df-singer-300x300.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Anh Chưa Thương Em Đến Vậy Đâu (Cover).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Dù Cho Mai Về Sau', N'buitruonglinh', 'https://www.nhaccuatui.com/bai-hat/du-cho-mai-ve-sau-buitruonglinh.vxd6Wne6Z8Pq.html', 'https://stream.nixcdn.com/NhacCuaTui1006/DuChoMaiVeSau-buitruonglinh-6818907.mp3?st=_M0Rha_2GFySVDTfP62j8w&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2020/11/16/a/9/3/7/1605520682897.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Dù Cho Mai Về Sau.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Từng Yêu', N'Phan Duy Anh', 'https://www.nhaccuatui.com/bai-hat/tung-yeu-phan-duy-anh.tnvcYCYt7lmv.html', 'https://stream.nixcdn.com/NhacCuaTui983/TungYeu-PhanDuyAnh-5989256.mp3?st=uFxTLKNYlZye106SbKPKLg&e=1670306197', 'https://avatar-ex-swe.nixcdn.com/song/2019/07/03/7/5/b/e/1562146897414.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Từng Yêu.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Anh Nhớ Ra (Feat. Trang)', N'Vũ.', 'https://www.nhaccuatui.com/bai-hat/anh-nho-ra-feat-trang-vu.5WaXO2cz4RkK.html', 'https://stream.nixcdn.com/Warner_Audio109/AnhNhoRaFeatTrang-Vu-8279183.mp3?st=Q6sueBZsyhMPhAHFWhhkeA&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/09/07/b/d/f/6/1662533204017.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Anh Nhớ Ra (Feat. Trang).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Mah Boo', N'Phạm Việt Thắng', 'https://www.nhaccuatui.com/bai-hat/mah-boo-pham-viet-thang.PEExWA1kCpZd.html', 'https://stream.nixcdn.com/NhacCuaTui2031/MahBoo1-PhamVietThang-8141071.mp3?st=Adb2OpAJyZess-1mVrWyEg&e=1670306226', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/26/9/2/5/2/1666767345414.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Mah Boo.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Khá Khen', N'Tóc Tiên', 'https://www.nhaccuatui.com/bai-hat/kha-khen-toc-tien.raVpEXjRaGe7.html', 'https://stream.nixcdn.com/NhacCuaTui2030/KhaKhen-TocTien-8179125.mp3?st=icaP4VMK7EaE1wtAnHebng&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/31/8/3/d/0/1667190762287.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Khá Khen.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Lâu Lâu Nhắc Lại', N'Hà Nhi, Khói', 'https://www.nhaccuatui.com/bai-hat/lau-lau-nhac-lai-ha-nhi-ft-khoi.4khr4rBgaRCY.html', 'https://stream.nixcdn.com/NhacCuaTui2028/LauLauNhacLai-HaNhiKhoi-7948601.mp3?st=hOdfaA9zJafstEzCJ-QX2Q&e=1670306322', 'https://avatar-ex-swe.nixcdn.com/song/2022/09/23/2/3/3/a/1663907072556.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Lâu Lâu Nhắc Lại.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Bản Chất Thật', N'Keyo', 'https://www.nhaccuatui.com/bai-hat/ban-chat-that-keyo.Auo0jqbru6w5.html', 'https://stream.nixcdn.com/NhacCuaTui2031/BanChatThat-KyoVietNam-8246824.mp3?st=NPvFJ0dLFJLabBjxu0hgjA&e=1670306322', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/12/d/0/3/4/1668269541586.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Bản Chất Thật.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Vì Anh Đâu Có Biết', N'Madihu, Vũ', 'https://www.nhaccuatui.com/bai-hat/vi-anh-dau-co-biet-madihu-ft-vu.8qjZjYGWp4U8.html', 'https://stream.nixcdn.com/Warner_Audio99/ViAnhDauCoBiet-MadihuVu-8095009.mp3?st=7nvz87bP669f6OjfVG4Eyw&e=1670306295', 'https://avatar-ex-swe.nixcdn.com/song/2022/08/05/5/b/8/a/1659665880915.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Vì Anh Đâu Có Biết.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Đừng Lo Nhé Có Anh Đây (Demo)', N'Thiên Tú', 'https://www.nhaccuatui.com/bai-hat/dung-lo-nhe-co-anh-day-demo-thien-tu.qUZLMadhcUdC.html', 'https://stream.nixcdn.com/NhacCuaTui2032/DungLoNheCoAnhDayDemo-ThienTu-8330950.mp3?st=uQP-hRRSztP-j1us48_D-g&e=1670306322', 'https://stc-id.nixcdn.com/v11/images/df-singer-300x300.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Đừng Lo Nhé Có Anh Đây (Demo).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Cuối Cùng Thì (Lofi Version)', N'Jack - J97', 'https://www.nhaccuatui.com/bai-hat/cuoi-cung-thi-lofi-version-jack-j97.GQuHiitI45vu.html', 'https://stream.nixcdn.com/NhacCuaTui2031/CuoiCungThiLofiVersion-JackJ97-8219542.mp3?st=i0DNN0vIfs0tWWhOAqX2JA&e=1670306322', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/08/2/b/3/8/1667884230613.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Cuối Cùng Thì (Lofi Version).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Bước Qua Mùa Cô Đơn', N'Vũ', 'https://www.nhaccuatui.com/bai-hat/buoc-qua-mua-co-don-vu.RlabF9aqNM03.html', 'https://stream.nixcdn.com/Warner_Audio86/BuocQuaMuaCoDon-Vu-7847965.mp3?st=KxIeNzY1mHhcPBUdLRZUWA&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2020/12/11/4/0/f/e/1607643612541.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Bước Qua Mùa Cô Đơn.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'quý cô say xỉn (secret sunday)', N'Phùng Khánh Linh', 'https://www.nhaccuatui.com/bai-hat/quy-co-say-xin-secret-sunday-phung-khanh-linh.YttqR7gRcLLH.html', 'https://stream.nixcdn.com/NhacCuaTui2031/QuyCoSayXinsecretSunday-PhungKhanhLinh-8246231.mp3?st=Rrf387LGU6fe2YPJYqQi6w&e=1670306322', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/10/7/f/f/e/1668087175408.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\quý cô say xỉn (secret sunday).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Đôi Bờ (XHTDRLX2)', N'Trúc Nhân', 'https://www.nhaccuatui.com/bai-hat/doi-bo-xhtdrlx2-truc-nhan.B0klUIfOe2MH.html', 'https://stream.nixcdn.com/Sony_Audio111/DoiBo-TrucNhan-8274396.mp3?st=cSxiKeWhAwDUJS3Iprv7HQ&e=1670306322', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/08/8/a/6/f/1667894608481.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Đôi Bờ (XHTDRLX2).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Lạ Lùng', N'Vũ', 'https://www.nhaccuatui.com/bai-hat/la-lung-vu.fDWBTegKpBDs.html', 'https://stream.nixcdn.com/NhacCuaTui935/LaLung-Vu-4749614.mp3?st=40AD36SSwXoyhNFh4sa-tg&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2018/01/26/1/8/9/0/1516930244148.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Lạ Lùng.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Ai Chung Tình Được Mãi', N'Đinh Tùng Huy, ACV', 'https://www.nhaccuatui.com/bai-hat/ai-chung-tinh-duoc-mai-dinh-tung-huy-ft-acv.6I3T7UZ7pmbm.html', 'https://stream.nixcdn.com/NhacCuaTui1027/AiChungTinhDuocMai-DinhTungHuyACV-7197858.mp3?st=0vecpw9RoG2K1CArnpUNtA&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/04/26/d/1/1/f/1650953841508.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Ai Chung Tình Được Mãi.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Không Cần Phải Nói Nhiều (The Goodboi Flip)', N'tlinh, Onionn', 'https://www.nhaccuatui.com/bai-hat/khong-can-phai-noi-nhieu-the-goodboi-flip-tlinh-ft-onionn.jU7ZUKjQmI5J.html', 'https://stream.nixcdn.com/NhacCuaTui2032/KhongCanPhaiNoiNhieuTheGoodboiFlip-tlinhOnionn-8307163.mp3?st=HDR0jQKqVM73TzcUCl2cEw&e=1670306322', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/22/a/f/3/4/1669107292327.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Không Cần Phải Nói Nhiều (The Goodboi Flip).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'CONG', N'Tóc Tiên', 'https://www.nhaccuatui.com/bai-hat/cong-toc-tien.x5TKXsRJebDl.html', 'https://stream.nixcdn.com/NhacCuaTui2030/CONG-TocTien-8178821.mp3?st=6Tc690HV0wSKZzTnEe2bew&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/31/8/3/d/0/1667190296688.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\CONG.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Ánh Sao Và Bầu Trời', N'T.R.I', 'https://www.nhaccuatui.com/bai-hat/anh-sao-va-bau-troi-tri.o3929Y38WDqC.html', 'https://stream.nixcdn.com/NhacCuaTui1021/AnhSaoVaBauTroi-TRI-7085073.mp3?st=9vh4KwI2hxIJFcfv0kCznQ&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2021/09/09/f/c/f/d/1631155238247.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Ánh Sao Và Bầu Trời.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Anh Mong', N'Ocean', 'https://www.nhaccuatui.com/bai-hat/anh-mong-ocean.KSZiavUpYoTC.html', 'https://stream.nixcdn.com/NhacCuaTui2030/AnhMong-OceanVietNam-8108182.mp3?st=cNncTffwHxG2cbUAfaT6fA&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/23/9/1/a/7/1666504632344.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Anh Mong.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Buồn Thì Cứ Khóc Đi (XHTDRLX2)', N'Trúc Nhân', 'https://www.nhaccuatui.com/bai-hat/buon-thi-cu-khoc-di-xhtdrlx2-truc-nhan.BY7gnjH9GJry.html', 'https://stream.nixcdn.com/Sony_Audio112/BuonThiCuKhocDi-TrucNhan-8280499.mp3?st=UgxwgPK2oG3rzAmFj12FFA&e=1670306322', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/15/7/7/d/e/1668490681657.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Buồn Thì Cứ Khóc Đi (XHTDRLX2).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Tòng Phu (Hoài Lâm Cover)', N'Keyo', 'https://www.nhaccuatui.com/bai-hat/tong-phu-hoai-lam-cover-keyo.lD8g4m817Bqk.html', 'https://stream.nixcdn.com/NhacCuaTui2029/TongPhuHoaiLamCover-KeyoVietNam-8074589.mp3?st=qXkMpfqPRXO-q6XYYiI5bw&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/singer/avatar/2019/06/17/b/2/a/b/1560741315819.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Tòng Phu (Hoài Lâm Cover).mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Như Anh Đã Mong Chờ', N'Hari Won', 'https://www.nhaccuatui.com/bai-hat/nhu-anh-da-mong-cho-hari-won.p4aSg0yzwuMu.html', 'https://stream.nixcdn.com/NhacCuaTui2031/NhuAnhDaMongCho-HariWon-8246821.mp3?st=fmRRgstqxGUrfV4-7hs2lA&e=1670306267', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/12/d/0/3/4/1668269383467.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Như Anh Đã Mong Chờ.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Cứ Chill Thôi', N'Chillies, Suni Hạ Linh, Rhymastic', 'https://www.nhaccuatui.com/bai-hat/cu-chill-thoi-chillies-ft-suni-ha-linh-ft-rhymastic.I0ZXAn60MifT.html', 'https://stream.nixcdn.com/Warner_Audio33/CuChillThoi-ChilliesSuniHaLinhRhymastic-6330366.mp3?st=PHjy5fVFWXkLu9p3rFwsOA&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2020/07/13/a/f/7/f/1594611971401.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Cứ Chill Thôi.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Sao Ta Không Trân Trọng', N'Lê Quang Phú, Ngô Hoàng', 'https://www.nhaccuatui.com/bai-hat/sao-ta-khong-tran-trong-le-quang-phu-ft-ngo-hoang.No3wtwPLi1ye.html', 'https://stream.nixcdn.com/NhacCuaTui2031/SaoTaKhongTranTrong-LeQuangPhuNgoHoang-8267606.mp3?st=AwOtqx7QeEZGKhJikwE0xQ&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/15/8/2/d/b/1668530368255.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Sao Ta Không Trân Trọng.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Đố Em Kiếm Ai Yêu Em Như Anh', N'Jokes Bii, Phát Hồ', 'https://www.nhaccuatui.com/bai-hat/do-em-kiem-ai-yeu-em-nhu-anh-jokes-bii-ft-phat-ho.0ZfKS60QjXF2.html', 'https://stream.nixcdn.com/NhacCuaTui2031/DoEmKiemAiYeuEmNhuAnh-JokesBiiPhatHo-8212400.mp3?st=ydt8PkZ1OopcL-Pwer7vEg&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/07/e/d/4/3/1667810702792.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Đố Em Kiếm Ai Yêu Em Như Anh.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Chúng Ta Không Thuộc Về Nhau', N'Sơn Tùng M-TP', 'https://www.nhaccuatui.com/bai-hat/chung-ta-khong-thuoc-ve-nhau-son-tung-m-tp.Qtd3XdEr5XtP.html', 'https://stream.nixcdn.com/NhacCuaTui925/ChungTaKhongThuocVeNhau-SonTungMTP-4528181.mp3?st=9h4chWBbdYNUTVzeklVcEw&e=1670306322', 'https://avatar-ex-swe.nixcdn.com/song/2017/08/21/9/2/c/9/1503305440699.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Chúng Ta Không Thuộc Về Nhau.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Vệ Tinh', N'HIEUTHUHAI, Hoàng Tôn, Kewtiie', 'https://www.nhaccuatui.com/bai-hat/ve-tinh-hieuthuhai-ft-hoang-ton-ft-kewtiie.76ws1gfIyq3t.html', 'https://stream.nixcdn.com/NhacCuaTui2030/VeTinh-HIEUTHUHAIHoangTonKewtiie-7730914.mp3?st=o3j9-CLpx2nyNmFpsybHhg&e=1670306322', 'https://avatar-ex-swe.nixcdn.com/song/2022/08/09/7/f/a/3/1660019524774.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Vệ Tinh.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Em Là Nhất Miền Tây', N'Võ Lê Mi, Jin Tuấn Nam', 'https://www.nhaccuatui.com/bai-hat/em-la-nhat-mien-tay-vo-le-mi-ft-jin-tuan-nam.LTq8U3tHVohI.html', 'https://stream.nixcdn.com/NhacCuaTui2028/EmLaNhatMienTay-VoLeMiJinTuanNam-7851479.mp3?st=2DsnrvYTs78JePnKK4AHbg&e=1670306215', 'https://avatar-ex-swe.nixcdn.com/song/2022/09/19/8/d/2/9/1663602284110.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Em Là Nhất Miền Tây.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Để Mị Nói Cho Mà Nghe', N'Hoàng Thùy Linh', 'https://www.nhaccuatui.com/bai-hat/de-mi-noi-cho-ma-nghe-hoang-thuy-linh.cxycw7eSvV7t.html', 'https://stream.nixcdn.com/Sony_Audio67/DeMiNoiChoMaNghe-HoangThuyLinh-6153588.mp3?st=zjRDqoaoT0EFuR6n-nfk5w&e=1670306311', 'https://avatar-ex-swe.nixcdn.com/song/2019/06/20/5/9/0/b/1560999333698.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Để Mị Nói Cho Mà Nghe.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Đường Tôi Chở Em Về', N'buitruonglinh', 'https://www.nhaccuatui.com/bai-hat/duong-toi-cho-em-ve-buitruonglinh.EEZTcFO2Ajfc.html', 'https://stream.nixcdn.com/Unv_Audio164/DuongTaChoEmVe-buitruonglinh-6318765.mp3?st=hy-u1eb6c0tbuowhffnVyw&e=1670306046', 'https://avatar-ex-swe.nixcdn.com/song/2020/07/02/5/d/c/9/1593687560557.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Đường Tôi Chở Em Về.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'3107', N'W/n, DuongG, Nâu', 'https://www.nhaccuatui.com/bai-hat/3107-wn-ft-duongg-ft-nau.HkDuAPT28WB5.html', 'https://stream.nixcdn.com/NhacCuaTui996/3107-WnDuonggNau-6099150.mp3?st=FPpbTtpLCMkKnmlzCXmVbQ&e=1670306251', 'https://avatar-ex-swe.nixcdn.com/song/2020/02/25/6/c/7/7/1582603846517.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\3107.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Tấm Lòng Son', N'H-Kray', 'https://www.nhaccuatui.com/bai-hat/tam-long-son-h-kray.PehXmwkfvWZ6.html', 'https://stream.nixcdn.com/NhacCuaTui1026/TamLongSon-HKray-7160658.mp3?st=Vbnt3jWuSFxP9L8A-Eur6g&e=1670306322', 'https://avatar-ex-swe.nixcdn.com/song/2022/03/26/2/8/7/c/1648256471185.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Tấm Lòng Son.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Buồn Không Thể Buông', N'Trung Quân, MiiNa (DREAMeR), DREAMeR', 'https://www.nhaccuatui.com/bai-hat/buon-khong-the-buong-trung-quan-ft-miina-dreamer-ft-dreamer.Ay3nCSfRQsnt.html', 'https://stream.nixcdn.com/NhacCuaTui2032/BuonKhongTheBuong-TrungQuanMiinaDREAMeRVietNam-8313768.mp3?st=5ySNUFP51Tpjy0ynrbCQkg&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/24/0/7/f/d/1669269816238.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Buồn Không Thể Buông.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Hối Tiếc', N'Giang Hồng Ngọc', 'https://www.nhaccuatui.com/bai-hat/hoi-tiec-giang-hong-ngoc.KM8jRQUIYU46.html', 'https://stream.nixcdn.com/NhacCuaTui2030/HoiTiec-GiangHongNgoc-8109023.mp3?st=2S27FaPt4eRbYKcIdyk31w&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/24/a/8/3/1/1666581184311.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Hối Tiếc.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Lời Hứa Chưa Phai', N'Kendy T, Ngọc Xuân', 'https://www.nhaccuatui.com/bai-hat/loi-hua-chua-phai-kendy-t-ft-ngoc-xuan.6UKn9Cn3Zsui.html', 'https://stream.nixcdn.com/NhacCuaTui2031/LoiHuaChuaPhai-KendyTNgocXuan-8233544.mp3?st=zLIakfk1HgNP4uRVsztmlw&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/08/8/9/e/f/1667919367344.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Lời Hứa Chưa Phai.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Vẽ Đường Cong', N'Trúc Nhân', 'https://www.nhaccuatui.com/bai-hat/ve-duong-cong-truc-nhan.BcIQbHNRVePy.html', 'https://stream.nixcdn.com/NhacCuaTui2030/VeDuongCong-TrucNhan-8159099.mp3?st=M95uJwjatT7Z_ajL4IXlzg&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/27/0/3/8/0/1666855578395.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Vẽ Đường Cong.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Anh Không Thể Ngờ', N'Đinh Tùng Huy, ACV', 'https://www.nhaccuatui.com/bai-hat/anh-khong-the-ngo-dinh-tung-huy-ft-acv.tZ3q3LFhDeRY.html', 'https://stream.nixcdn.com/NhacCuaTui2030/AnhKhongTheNgo-DinhTungHuyACV-8195785.mp3?st=fO1Pao4JQnN1ziS_GgWA9Q&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/02/3/e/7/d/1667380640558.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Anh Không Thể Ngờ.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Gần Bên Anh', N'Sơn Pinky', 'https://www.nhaccuatui.com/bai-hat/gan-ben-anh-son-pinky.eSwXDEpRdkbd.html', 'https://stream.nixcdn.com/NhacCuaTui2030/GanBenAnh-SonPinky-8108183.mp3?st=HH7DjJHJEf-a-uaeNLEIyA&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/23/9/1/a/7/1666505317748.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Gần Bên Anh.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Hình Như Ta Thích Nhau', N'Doãn Hiếu, BMZ', 'https://www.nhaccuatui.com/bai-hat/hinh-nhu-ta-thich-nhau-doan-hieu-ft-bmz.tWJd9gt7m2Tv.html', 'https://stream.nixcdn.com/NhacCuaTui2030/HinhNhuTaThichNhau-DoanHieuBMZ-8107565.mp3?st=HuFcmXinqU8WZWaPCCtCCw&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/21/e/a/b/9/1666336378970.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Hình Như Ta Thích Nhau.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Đau Lòng', N'H-Kray', 'https://www.nhaccuatui.com/bai-hat/dau-long-h-kray.gYfNTQ87u5u0.html', 'https://stream.nixcdn.com/NhacCuaTui2031/DauLong-HKray-8211792.mp3?st=Ujncs6hHTK5Z53NmnCW9Zw&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/07/e/d/4/3/1667809771494.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Đau Lòng.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Đi Đâu Cũng Được', N'Du Uyên, Nguyễn Thương', 'https://www.nhaccuatui.com/bai-hat/di-dau-cung-duoc-du-uyen-ft-nguyen-thuong.9bzzi8s4RyPi.html', 'https://stream.nixcdn.com/NhacCuaTui2031/DiDauCungDuoc-DuUyenNguyenThuong-8237153.mp3?st=CNexmbvuKxvru1YyjzTbRg&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/09/b/4/f/f/1667986121289.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Đi Đâu Cũng Được.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Gác Lại Âu Lo', N'Da LAB, Miu Lê', 'https://www.nhaccuatui.com/bai-hat/gac-lai-au-lo-da-lab-ft-miu-le.1uWWUf6ZAHC4.html', 'https://stream.nixcdn.com/NhacCuaTui1001/GacLaiAuLo-DaLABMiuLe-6360815.mp3?st=34doJ9lJgozSxQV4cZoeKQ&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2020/07/24/f/6/5/1/1595564868985.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Gác Lại Âu Lo.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Nhìn Về Phía Em', N'Phan Duy Anh, ACV', 'https://www.nhaccuatui.com/bai-hat/nhin-ve-phia-em-phan-duy-anh-ft-acv.Cu6y8UqL0Qd9.html', 'https://stream.nixcdn.com/NhacCuaTui2030/NhinVePhiaEm-PhanDuyAnhACV-8093994.mp3?st=m6cKXQlOueIzdw211IWcOA&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/20/2/4/1/e/1666236020663.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Nhìn Về Phía Em.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Ngàn Thu', N'Toky', 'https://www.nhaccuatui.com/bai-hat/ngan-thu-toky.219MuAeQ4x0o.html', 'https://stream.nixcdn.com/NhacCuaTui2031/NganThu-Toky-8266241.mp3?st=Uf-EkLsnRbDUJ_mOoyq0SA&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/11/15/8/2/d/b/1668521414130.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Ngàn Thu.mp3')
INSERT INTO SONG (SONGNAME, SINGERNAME, SONGURL, DOWNLOADURL, IMAGEURL, SAVEPATH) VALUES (N'Đừng Bắt Anh Mạnh Mẽ (Remake)', N'Hồ Quang Hiếu', 'https://www.nhaccuatui.com/bai-hat/dung-bat-anh-manh-me-remake-ho-quang-hieu.8THc39ZIpqgQ.html', 'https://stream.nixcdn.com/NhacCuaTui2030/DungBatAnhManhMeRemake-HoQuangHieu-8082449.mp3?st=1qQ41plE0prPKTdv7dTJ0A&e=1670306049', 'https://avatar-ex-swe.nixcdn.com/song/2022/10/17/7/9/e/f/1666022454100.jpg', N'C:\Users\ADMIN\Desktop\test2\MusicPlayer\bin\Debug\Song\Đừng Bắt Anh Mạnh Mẽ (Remake).mp3')

UPDATE SONG 
SET SAVEPATH = NULL