//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LASTEST
    {
        public int SONGID { get; set; }
        public int USERID { get; set; }
        public Nullable<int> SEQ { get; set; }
    
        public virtual SONG SONG { get; set; }
        public virtual USER USER { get; set; }
    }
}
