//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPlayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO
    {
        public int VIDEOID { get; set; }
        public string VIDEONAME { get; set; }
        public string SINGERNAME { get; set; }
        public string VIDEOURL { get; set; }
        public string DOWNLOADURL { get; set; }
        public string IMAGEURL { get; set; }
        public string SAVEPATH { get; set; }
        public Nullable<double> DURATION { get; set; }
        public Nullable<double> POSITION { get; set; }
        public string GENRE { get; set; }
    }
}
